grobid:
  service:
    log:
      level: DEBUG
  grobidHome: "/opt/grobid/grobid-home"
  modelPath: "/opt/grobid/grobid-home/models"
  tempPath: "/opt/grobid/grobid-home/tmp"
  nativelibrary: "lib"

# GROBID Dropwizard configuration
server:
  # HTTP connector for application traffic
  applicationConnectors:
    - type: http
      port: ${PORT:-8070}

  # HTTP connector for admin/health checks
  adminConnectors:
    - type: http
      port: 8071

logging:
  level: DEBUG               # Global root logger at DEBUG level
  loggers:
    io.grobid.service: DEBUG  # Debug logs for GROBID service components
    org.grobid.service: DEBUG