grobid:
  pdf:
    pdfalto:
      path: "/usr/local/bin/pdfalto_server"
      memoryLimitMb: 6096
      timeoutSec: 120
  grobidHome: "."

server:
  type: custom
  applicationConnectors:
    - type: http
      port: 8070      # ← 環境変数参照を削除（純粋に整数）
  adminConnectors:
    - type: http
      port: 8071

logging:
  level: INFO