# ─────────────────────────────────────────────────────────────
# GROBID メイン設定
# ─────────────────────────────────────────────────────────────
grobid:
  pdf:
    pdfalto:
      # バイナリの絶対パス（Dockerfile と合わせる）
      path: "/usr/local/bin/pdfalto_server"
      memoryLimitMb: 6096
      timeoutSec: 120

  grobidHome: "."
  
server:
  type: custom
  applicationConnectors:
    - type: http
      # 必ず整数で指定（文字列や ${…} は使わない）
      port: 8070
  adminConnectors:
    - type: http
      port: 8071

logging:
  level: INFO
      port: ${PORT:-8070}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8071}
